---
# tasks file for pkindustries.apache
- name: Install apache on Debian
  apt:
   name: "{{ apache_package_deb }}"
   state: present
  when: ansible_os_family == "Debian"

- name: Install apache on RHEL  
  yum:
    name: "{{ apache_package_rhel }}"
    state: present
  when: ansible_os_family == "RedHat" 

- name: Set service name for Debian
  set_fact:
    apache_package: "{{ apache_package_deb }}"
  when: ansible_os_family == "Debian"

- name: Set service name for RHEL
  set_fact:
    apache_package: "{{ apache_package_rhel }}"
  when: ansible_os_family == "RedHat" 

- name: Start & Enable
  service:
    name: "{{ apache_package }}"
    state: started
    enabled: yes

- name: Test by print
  debug:
    msg: Firing notification for RedHat
  notify: restart_rhel_apache
  when: ansible_os_family == "RedHat"

- name: Test by print
  debug:
    msg: Firing notification for Debian
  notify: restart_deb_apache
  when: ansible_os_family == "Debian"